import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-ap-duplicate-payment-vendor-refund-recovery",
  "engine": "recovery",
  "title": "AP Duplicate Payment & Vendor Refund Recovery",
  "shortTitle": "AP Duplicate Payment and Vendor Refund Recovery",
  "tagline": "Quantify, recover, and prevent financial leakage through ap duplicate payment & vendor refund recovery",
  "industry": "Accounts Payable Recovery",
  "uiPort": 4591,
  "apiPort": 5591,
  "accent": "#4f46e5",
  "currency": "USD",
  "primaryOutcome": "AP Duplicate Payment & Vendor Refund Recovery converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect vendor masters, invoices, purchase orders, receipts, payments, expense reimbursements, statements, credits, refunds, and correspondence in one accountable recovery workflow.",
  "calculation": {
    "actualKey": "paidAmount",
    "expectedKey": "supportedAmount",
    "actualLabel": "Paid or Debited Amount",
    "expectedLabel": "Supported Unique Liability",
    "varianceLabel": "Potential recovery or avoided cost",
    "direction": "actual-minus-expected",
    "finding": "AP Duplicate Payment & Vendor Refund Recovery evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective governing agreement and applicable rules",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare and submit the recovery or correction package",
      "Track counterparty response and reconcile realized outcome"
    ]
  }
},[
feature("vendor-master-normalization","ADP01","Vendor master normalization","Execute vendor master normalization using vendor masters, invoices, purchase orders, receipts, payments, expense reimbursements, statements, credits, refunds, and correspondence.","Produce a governed vendor master normalization decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Vendor / Payment Population","text","Vendor / Payment Population · Standard Case"],["caseReference","Vendor master normalization Reference","text","ADP01-2026-001"],["paidAmount","Paid or Debited Amount","currency",420000],["supportedAmount","Supported Unique Liability","currency",361200],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["Vendor master normalization case","Invoice and payment ingestion case","Exact duplicate detection case","Fuzzy invoice matching case","Split-invoice detection case"]}),
feature("invoice-and-payment-ingestion","ADP02","Invoice and payment ingestion","Execute invoice and payment ingestion using vendor masters, invoices, purchase orders, receipts, payments, expense reimbursements, statements, credits, refunds, and correspondence.","Produce a governed invoice and payment ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Vendor / Payment Population","text","Vendor / Payment Population · Standard Case"],["caseReference","Invoice and payment ingestion Reference","text","ADP02-2026-001"],["paidAmount","Paid or Debited Amount","currency",420000],["supportedAmount","Supported Unique Liability","currency",361200],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["Vendor master normalization case","Invoice and payment ingestion case","Exact duplicate detection case","Fuzzy invoice matching case","Split-invoice detection case"]}),
feature("exact-duplicate-detection","ADP03","Exact duplicate detection","Execute exact duplicate detection using vendor masters, invoices, purchase orders, receipts, payments, expense reimbursements, statements, credits, refunds, and correspondence.","Produce a governed exact duplicate detection decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Vendor / Payment Population","text","Vendor / Payment Population · Standard Case"],["caseReference","Exact duplicate detection Reference","text","ADP03-2026-001"],["paidAmount","Paid or Debited Amount","currency",420000],["supportedAmount","Supported Unique Liability","currency",361200],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["Vendor master normalization case","Invoice and payment ingestion case","Exact duplicate detection case","Fuzzy invoice matching case","Split-invoice detection case"]}),
feature("fuzzy-invoice-matching","ADP04","Fuzzy invoice matching","Execute fuzzy invoice matching using vendor masters, invoices, purchase orders, receipts, payments, expense reimbursements, statements, credits, refunds, and correspondence.","Produce a governed fuzzy invoice matching decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Vendor / Payment Population","text","Vendor / Payment Population · Standard Case"],["caseReference","Fuzzy invoice matching Reference","text","ADP04-2026-001"],["paidAmount","Paid or Debited Amount","currency",420000],["supportedAmount","Supported Unique Liability","currency",361200],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["Vendor master normalization case","Invoice and payment ingestion case","Exact duplicate detection case","Fuzzy invoice matching case","Split-invoice detection case"]}),
feature("split-invoice-detection","ADP05","Split-invoice detection","Execute split-invoice detection using vendor masters, invoices, purchase orders, receipts, payments, expense reimbursements, statements, credits, refunds, and correspondence.","Produce a governed split-invoice detection decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Vendor / Payment Population","text","Vendor / Payment Population · Standard Case"],["caseReference","Split-invoice detection Reference","text","ADP05-2026-001"],["paidAmount","Paid or Debited Amount","currency",420000],["supportedAmount","Supported Unique Liability","currency",361200],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["Vendor master normalization case","Invoice and payment ingestion case","Exact duplicate detection case","Fuzzy invoice matching case","Split-invoice detection case"]}),
feature("duplicate-expense-analysis","ADP06","Duplicate expense analysis","Execute duplicate expense analysis using vendor masters, invoices, purchase orders, receipts, payments, expense reimbursements, statements, credits, refunds, and correspondence.","Produce a governed duplicate expense analysis decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Vendor / Payment Population","text","Vendor / Payment Population · Standard Case"],["caseReference","Duplicate expense analysis Reference","text","ADP06-2026-001"],["paidAmount","Paid or Debited Amount","currency",420000],["supportedAmount","Supported Unique Liability","currency",361200],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["Vendor master normalization case","Invoice and payment ingestion case","Exact duplicate detection case","Fuzzy invoice matching case","Split-invoice detection case"]}),
feature("vendor-credit-balance-discovery","ADP07","Vendor credit-balance discovery","Execute vendor credit-balance discovery using vendor masters, invoices, purchase orders, receipts, payments, expense reimbursements, statements, credits, refunds, and correspondence.","Produce a governed vendor credit-balance discovery decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Vendor / Payment Population","text","Vendor / Payment Population · Standard Case"],["caseReference","Vendor credit-balance discovery Reference","text","ADP07-2026-001"],["paidAmount","Paid or Debited Amount","currency",420000],["supportedAmount","Supported Unique Liability","currency",361200],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["Vendor master normalization case","Invoice and payment ingestion case","Exact duplicate detection case","Fuzzy invoice matching case","Split-invoice detection case"]}),
feature("statement-to-ledger-reconciliation","ADP08","Statement-to-ledger reconciliation","Execute statement-to-ledger reconciliation using vendor masters, invoices, purchase orders, receipts, payments, expense reimbursements, statements, credits, refunds, and correspondence.","Produce a governed statement-to-ledger reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Vendor / Payment Population","text","Vendor / Payment Population · Standard Case"],["caseReference","Statement-to-ledger reconciliation Reference","text","ADP08-2026-001"],["paidAmount","Paid or Debited Amount","currency",420000],["supportedAmount","Supported Unique Liability","currency",361200],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["Vendor master normalization case","Invoice and payment ingestion case","Exact duplicate detection case","Fuzzy invoice matching case","Split-invoice detection case"]}),
feature("cancelled-payment-validation","ADP09","Cancelled payment validation","Execute cancelled payment validation using vendor masters, invoices, purchase orders, receipts, payments, expense reimbursements, statements, credits, refunds, and correspondence.","Produce a governed cancelled payment validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Vendor / Payment Population","text","Vendor / Payment Population · Standard Case"],["caseReference","Cancelled payment validation Reference","text","ADP09-2026-001"],["paidAmount","Paid or Debited Amount","currency",420000],["supportedAmount","Supported Unique Liability","currency",361200],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["Vendor master normalization case","Invoice and payment ingestion case","Exact duplicate detection case","Fuzzy invoice matching case","Split-invoice detection case"]}),
feature("recovery-case-management","ADP10","Recovery case management","Execute recovery case management using vendor masters, invoices, purchase orders, receipts, payments, expense reimbursements, statements, credits, refunds, and correspondence.","Produce a governed recovery case management decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Vendor / Payment Population","text","Vendor / Payment Population · Standard Case"],["caseReference","Recovery case management Reference","text","ADP10-2026-001"],["paidAmount","Paid or Debited Amount","currency",420000],["supportedAmount","Supported Unique Liability","currency",361200],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["Vendor master normalization case","Invoice and payment ingestion case","Exact duplicate detection case","Fuzzy invoice matching case","Split-invoice detection case"]}),
feature("vendor-correspondence-generation","ADP11","Vendor correspondence generation","Execute vendor correspondence generation using vendor masters, invoices, purchase orders, receipts, payments, expense reimbursements, statements, credits, refunds, and correspondence.","Produce a governed vendor correspondence generation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Vendor / Payment Population","text","Vendor / Payment Population · Standard Case"],["caseReference","Vendor correspondence generation Reference","text","ADP11-2026-001"],["paidAmount","Paid or Debited Amount","currency",420000],["supportedAmount","Supported Unique Liability","currency",361200],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["Vendor master normalization case","Invoice and payment ingestion case","Exact duplicate detection case","Fuzzy invoice matching case","Split-invoice detection case"]}),
feature("refund-and-credit-tracking","ADP12","Refund and credit tracking","Execute refund and credit tracking using vendor masters, invoices, purchase orders, receipts, payments, expense reimbursements, statements, credits, refunds, and correspondence.","Produce a governed refund and credit tracking decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Vendor / Payment Population","text","Vendor / Payment Population · Standard Case"],["caseReference","Refund and credit tracking Reference","text","ADP12-2026-001"],["paidAmount","Paid or Debited Amount","currency",420000],["supportedAmount","Supported Unique Liability","currency",361200],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["Vendor master normalization case","Invoice and payment ingestion case","Exact duplicate detection case","Fuzzy invoice matching case","Split-invoice detection case"]}),
feature("general-ledger-reconciliation","ADP13","General-ledger reconciliation","Execute general-ledger reconciliation using vendor masters, invoices, purchase orders, receipts, payments, expense reimbursements, statements, credits, refunds, and correspondence.","Produce a governed general-ledger reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Vendor / Payment Population","text","Vendor / Payment Population · Standard Case"],["caseReference","General-ledger reconciliation Reference","text","ADP13-2026-001"],["paidAmount","Paid or Debited Amount","currency",420000],["supportedAmount","Supported Unique Liability","currency",361200],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["Vendor master normalization case","Invoice and payment ingestion case","Exact duplicate detection case","Fuzzy invoice matching case","Split-invoice detection case"]}),
feature("preventive-payment-controls","ADP14","Preventive payment controls","Execute preventive payment controls using vendor masters, invoices, purchase orders, receipts, payments, expense reimbursements, statements, credits, refunds, and correspondence.","Produce a governed preventive payment controls decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Vendor / Payment Population","text","Vendor / Payment Population · Standard Case"],["caseReference","Preventive payment controls Reference","text","ADP14-2026-001"],["paidAmount","Paid or Debited Amount","currency",420000],["supportedAmount","Supported Unique Liability","currency",361200],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["Vendor master normalization case","Invoice and payment ingestion case","Exact duplicate detection case","Fuzzy invoice matching case","Split-invoice detection case"]}),
feature("vendor-and-root-cause-analytics","ADP15","Vendor and root-cause analytics","Execute vendor and root-cause analytics using vendor masters, invoices, purchase orders, receipts, payments, expense reimbursements, statements, credits, refunds, and correspondence.","Produce a governed vendor and root-cause analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Vendor / Payment Population","text","Vendor / Payment Population · Standard Case"],["caseReference","Vendor and root-cause analytics Reference","text","ADP15-2026-001"],["paidAmount","Paid or Debited Amount","currency",420000],["supportedAmount","Supported Unique Liability","currency",361200],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["Vendor master normalization case","Invoice and payment ingestion case","Exact duplicate detection case","Fuzzy invoice matching case","Split-invoice detection case"]})
]);
